<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>com.studentteambeta</groupId>
  <artifactId>student-team-beta</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <sonar.coverage.exclusions>
      **/*Application.java,

      **/services/booking-service/src/main/java/com/classroom/booking_service/entity/**,
      **/services/booking-service/src/main/java/com/classroom/booking_service/dto/**,
      **/services/booking-service/src/main/java/com/classroom/booking_service/config/**,
      **/services/booking-service/src/main/java/com/classroom/booking_service/exception/**,
      **/services/booking-service/src/main/java/com/classroom/booking_service/security/JwtService.java,
      **/services/booking-service/src/main/java/com/classroom/booking_service/security/JwtAuthenticationFilter.java,

      **/services/room-service/src/main/java/com/classroom/room_service/entity/**,
      **/services/room-service/src/main/java/com/classroom/room_service/dto/**,
      **/services/room-service/src/main/java/com/classroom/room_service/config/**,
      **/services/room-service/src/main/java/com/classroom/room_service/exception/**,
      **/services/room-service/src/main/java/com/classroom/room_service/security/JwtService.java,
      **/services/room-service/src/main/java/com/classroom/room_service/security/JwtAuthenticationFilter.java
    </sonar.coverage.exclusions>
  </properties>

  <modules>
    <module>services/config-server</module>
    <module>services/booking-service</module>
    <module>services/room-service</module>
    <module>services/karate-tests</module>
  </modules>

</project>
