server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false
    gateway:
      server:
        webmvc:
          routes:
            - id: room-service
              uri: lb://room-service
              predicates:
                - Path=/rooms, /rooms/**

            - id: booking-service
              uri: lb://booking-service
              predicates:
                - Path=/bookings, /bookings/**

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth, /auth/**

jwt:
  secret: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS_123456"
